name: Generate Canyon Bikes HTML Report

on:
  push:
    branches:
      - main
  # Manual trigger
  workflow_dispatch:
    inputs:
      url:
        description: "URL to scrape"  # Optional, specify a file name
        required: false
  # Scheduled trigger (4 times a day)
  schedule:
    - cron: '0 0 * * *'
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pandas beautifulsoup4 requests selenium

    - name: Run script
      run: |
        python scrape.py  # Ensure your Python script is named `script.py`

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: HTML Report
        path: canyon_bikes_report.html
    - name: Send email
      uses: dawidd6/action-send-mail@v6
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        connection_url: smtp://${{ secrets.SMTP_USERNAME }}:${{ secrets.SMTP_PW }}@smtp.gmail.com:587
        # Required mail subject:
        subject: Canyon Bikes Report
        # Required recipients' addresses:
        to: mjt2007@gmail.com
        # Required sender full name (address can be skipped):
        from: Your Mama # <user@example.com>
        # Optional plain body:
        body:  |
          Hello,

          Please find attached the Canyon Bikes report.

          Best regards,
          Your Automation Script
        # Optional HTML body read from file:
        html_body: file://canyon_bikes_report.html